composer.json

See [laravel/framework](https://github.com/laravel/framework/blob/5.8/composer.json#L41).
(+ I just want it :heart:)

Make var-dumper a normal dependency

---

composer.json
config/app.php
config/cache.php
src/Acorn/Concerns/Bindings.php

Adds support for Illuminate Cache to Acorn core.

Adds Illuminate\Cache support

---

src/Acorn/Application.php
src/Acorn/Console/Commands/Command.php
src/Acorn/Console/Commands/GeneratorCommand.php
src/Acorn/Console/Commands/SummaryCommand.php
src/Acorn/Console/Kernel.php

* feature(console): implement custom summary command for displaying console help
* feature(console): add clearLine helper method
* feature(console): add exec helper method for executing processes
* feature(console): add task helper for creating styled tasks
* chore(console): remove unused schedule method/namespaces
* chore(docblock): clean up docblocks

Console Features/Improvements

---

src/Acorn/Bootstrap/Console.php

Not a given that WP_CLI is available

---

src/Acorn/Sage/SageServiceProvider.php

- fix(sage): Lower comments_template and get_search_form priority to play nice with plugins

comments_template and get_search_form priorities

---

src/Roots/Acorn/Application.php
src/Roots/Acorn/LazyLoader.php
src/Roots/Acorn/PackageManifest.php
src/Roots/Acorn/View/Composers/Concerns/Arrayable.php

- fix(composer): Fix PackageManifest autoloading Laravel package providers
- chore(lint): Add space after bangs

Fix PackageManifest autoloading leading to incompatibility

---

composer.json
src/Roots/Acorn/Filesystem/Filesystem.php

feat(fs-glob): suggest webmozart/glob

---

src/Roots/Acorn/Bootloader.php

Remove `static` return type

---

composer.json
src/Roots/Acorn/Filesystem/Filesystem.php
src/Roots/Acorn/Sage/Concerns/FiltersTemplates.php
tests/Filesystem/FilesystemTest.php

Switched to `$files->allFiles()`.
This is untested at the moment.
closes #118

fix(sage): support subdir post templates

---

src/Roots/Acorn/Console/Kernel.php

fix(console): Load commands that extend illuminate command

---

src/Roots/Acorn/Assets/Bundle.php

ref https://github.com/roots/bud/pull/977

fix(assets): leave asset paths w/ full URLs alone

---

src/Roots/Acorn/Bootloader.php

🐛 Register facades before providers

---

src/Roots/Acorn/Filesystem/Filesystem.php

♻️  rename variable

---

src/Roots/Acorn/Providers/AcornServiceProvider.php

🚑️ add missing `use ServiceProvider` statement

---

src/Roots/Acorn/Console/Kernel.php

Kinda forgot the most important part 🙈

🩹 add acorn:init to command list

---

src/Roots/Acorn/Bootstrap/RegisterConsole.php

🩹 support negatable options

---

src/Roots/Acorn/Assets/Asset/Asset.php
tests/Assets/AssetTest.php
tests/__snapshots__/AssetTest__it_can_get_a_relative_path__1.txt

Closes #227 
```php
$relative_path = asset('app.css')->relativePath(get_theme_file_path());
```

✨ add `Asset::relativePath()`

---

README.md
acorn.php

:bookmark: Bump plugin version
:pencil2: Fix typo in image alt tag in README

[2.x] :bookmark: Bump plugin version

---

composer.json
config/app.php
src/Roots/Acorn/Application.php
src/Roots/Acorn/Bootloader.php
src/Roots/Acorn/Console/Commands/stubs/paths/storage/framework/sessions/.gitignore
src/Roots/Acorn/Http/Kernel.php
src/Roots/Acorn/Providers/RouteServiceProvider.php

This adds `illuminate/routing` as a dependency.

➕ illuminate/routing:^9.0

---

src/Roots/Acorn/Bootloader.php

🐛 acorn stop breaking wp-cli pls

---

config/logging.php
src/Roots/Acorn/Application.php
src/Roots/Acorn/Bootloader.php
tests/Application/ApplicationTest.php

👨‍💻 Don't silently skip providers in local dev

---

composer.json

🔧 Change filp/whoops suggestion and dev-dependency to spatie/laravel-ignition

---

src/Roots/Acorn/Console/Kernel.php

🔧 Add routing related commands

---

src/Roots/Acorn/Console/Commands/AboutCommand.php
src/Roots/Acorn/Console/Kernel.php

👨‍💻 add `about` command

---

src/Roots/Acorn/Application.php
src/Roots/Acorn/Assets/Asset/TextAsset.php
src/Roots/Acorn/Bootloader.php
src/Roots/Acorn/Console/Commands/SummaryCommand.php
src/Roots/Acorn/Filesystem/Filesystem.php
src/Roots/Acorn/Filesystem/FilesystemServiceProvider.php
src/Roots/Acorn/PackageManifest.php
src/Roots/Acorn/Providers/AcornServiceProvider.php
src/Roots/Acorn/Sage/Concerns/FiltersBodyClass.php
src/Roots/Acorn/Sage/Concerns/FiltersEnqueues.php
src/Roots/Acorn/Sage/Concerns/FiltersTemplates.php
src/Roots/Acorn/Sage/ViewFinder.php
src/Roots/Acorn/View/Composers/Concerns/Arrayable.php
src/Roots/Acorn/View/FileViewFinder.php
src/Roots/Acorn/View/ViewServiceProvider.php

- 🎨 Use shorthanded functions where possible
- 🎨 Various random code cleanup

🎨 Tidy up codebase

---

composer.json

https://github.com/roots/acorn-prettify
https://roots.io/announcing-acorn-prettify/

🔧 Suggest installing acorn-prettify

---

src/Roots/Acorn/DefaultProviders.php

🩹 Fix missing migration providers

---

src/Roots/Acorn/DefaultProviders.php
tests/Application/DefaultProvidersTest.php

- ✅ Add test for replacing default providers
- 🩹 Fix duplicate `ViewServiceProvider` registration (Fixes #374)
- 🩹 Fix replacing default providers (Fixes #375)

🩹 Fix default provider discrepancies

---

README.md

Almost nothing, but you know 😁✨

Reflect Laravel version in README

---

src/Roots/Acorn/DefaultProviders.php

This doesn't appear to have any side effects nowdays.

🔧 Add the `FoundationServiceProvider` to the default providers (Fixes #409)

---

src/Roots/Acorn/Console/Commands/OptimizeClearCommand.php
src/Roots/Acorn/Console/Commands/OptimizeCommand.php

This mainly adds support for adding optimize tasks to service providers.

🧑‍💻 Use `OptimizeCommand::getOptimizedTasks` when getting optimize tasks

---

src/Roots/Acorn/Configuration/ApplicationBuilder.php

Updated `withRouting` to accept `$pages` and `$health` parameters, enhancing flexibility for routing configuration. This change ensures better alignment with the application's extended routing needs.

Refactor routing method to include new parameters.

---

src/Roots/Acorn/Application/Concerns/Bootable.php

Fix of issue: https://github.com/roots/acorn/issues/444

Terminate request (wordpress route) after request is handled.

---

bin/acorn
src/Roots/Acorn/Application/Concerns/Bootable.php

🩹 don't unintentionally boot acorn

---

composer.json

This adds `illuminate/auth` to the project to fix packages/providers that need to resolve `AuthManager`.

➕ Add `illuminate/auth` to the project
